### ISSUE TITLE
Version 7.0.0

### ISSUE THREAD

**Issue by pepibumur** [tuist/XcodeProj#396]
## Context 🕵️‍♀️
After several iterations of xcodeproj, there's still room for improvement in its API. Developers have shared issues and feedback that we can use to iterate on the 7th major version of the library. On this issue, I'm listing all the improvements/fixes that I think should make it into the next major version:

## What 🌱
- [x]  [**Change generated identifiers length to 24 (like Xcodes)**](https://github.com/tuist/xcodeproj/issues/392): Continuing with the effort of aligning the library closely to Xcode's behavior, we should use use the same length as Xcode for object unique identifiers.
  - PR: https://github.com/tuist/xcodeproj/pull/432
- [x]  **Swift 5 support**
  - Pull request: https://github.com/tuist/xcodeproj/pull/397/files
- [x]  [**Use upper camel case for project module name**](https://github.com/tuist/xcodeproj/issues/393): Follow the convention that most libraries stick to, using upper camel case for module names.
  - Pull request: https://github.com/tuist/xcodeproj/pull/398
- [x] [**Add support for RemoveRunnable**](https://github.com/tuist/xcodeproj/issues/276): Schemes can't specify a <RemoteRunnable> in the <LaunchAction>, and thus can't launch Sticker Packs.
  - PR: https://github.com/tuist/xcodeproj/pull/400
- [x] [**Auto generation of schemes**](https://github.com/tuist/xcodeproj/issues/115)
  - Pull request: https://github.com/tuist/xcodeproj/pull/399
- [x] Xcode 11 support

**Comment by pepibumur** [comment]
When we publish this version we'll need to make sure that [we let CocoaPods know](https://github.com/CocoaPods/cocoapods-trunk/issues/31) about the deprecation of the `xcodeproj` in favor of `XcodeProj.
